server:
  port: 8102

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:2001/eureka/,http://eureka-server-2:2002/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: stock-provider