server:
  port: 8802

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: stock-provider-2